<?php

return [
    'durable' => (bool) env('REALTIME_DURABLE', false),
    'connection' => env('REALTIME_DB_CONNECTION', env('DB_CONNECTION', 'resq_local')),
    'queue_connection' => env('REALTIME_QUEUE_CONNECTION', 'realtime_database'),
    'batch_size' => (int) env('REALTIME_BATCH_SIZE', 500),
    'read_cache' => (bool) env('REALTIME_READ_CACHE', false),
    'cache_store' => env('REALTIME_CACHE_STORE', 'redis'),
    'lease_seconds' => 120,
    'skip_locked' => (bool) env('REALTIME_SKIP_LOCKED', true),
    'topics' => [
        'household_status_logs' => ['households', 'mapping', 'dispatch', 'field-reports'],
        'member_disaster_statuses' => ['households', 'mapping', 'dispatch', 'field-reports'],
        'household_disasters' => ['households', 'mapping', 'dispatch', 'field-reports'],
        'households' => ['households', 'mapping', 'dispatch'],
        'household_members' => ['households', 'dispatch'],
        'responder_assignments' => ['dispatch', 'mapping', 'field-reports'],
        'responder_location_logs' => ['mapping', 'dispatch'],
        'responder_routes' => ['mapping', 'dispatch'],
        'route_coordinates' => ['mapping'],
        'responder_communication_logs' => ['communications'],
        'geotagged_locations' => ['mapping', 'households'],
        'evacuation_centers' => ['mapping', 'dispatch'],
        'rescue_teams' => ['mapping', 'dispatch', 'accounts'],
        'responders' => ['dispatch', 'accounts'],
        'resource_requests' => ['requests'],
        'weather_logs' => ['weather'],
        'disaster_events' => ['disasters'],
        'disaster_broadcasts' => ['disasters'],
        'rescue_priority_settings' => ['households', 'dispatch'],
        'landing_inquiries' => ['inquiries'],
        'users' => ['accounts'],
        'notifications' => [],
        'audit_logs' => [],
    ],
];
